# Generated by Django 5.2.10 on 2026-02-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reci_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reci_ing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.ingredient')),
                ('recipefield', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ledger.recipe')),
            ],
        ),
    ]
